name: publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 10.67.121.131
          username: xhunter
          password: ${{secrets.HOST_PASSWORD}}
          port: 22
          source: "."
          target: "/home/xhunter/payments/payments-frontend"

      - name: Deploying container
        uses: appleboy/ssh-action@master
        with:
          host: 10.67.121.131
          username: xhunter
          password: ${{secrets.HOST_PASSWORD}}
          port: 22
          script: |
            cd /home/xhunter/payments/payments-frontend/scripts
            chmod +x build.sh
            ./build.sh            

